### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by fregante** [yudppp/gulp-xto6#3]
Why use gulp when `xto6` can convert a [whole project](https://github.com/mohebifar/xto6#supported-features) without it?

**Comment by yudppp** [comment]
Use case is
- AltJS to ES6 (AltJS -> ES5 -> ES6)

And , It's easy for me to use.

thanks.

**Comment by fregante** [comment]
What I'm trying to say is that gulp solves the issue of running repetitive tasks while this kind of conversion probably happens once per project. This means that running these two commands once (copied/pasted from the respective projects' homepages) is easier/faster than setting up a whole gulpfile:

``` sh
coffee --compile --output es5/ src/
find es5/ -type f -not -path "*node_modules*" -name "*.js" -print0 | xargs -0 -I % xto6 % -o %
```
